# This file will store translated texts.
# These are mock translations corresponding to ORIGINAL_TEXTS.
# Some may contain intentional errors for QA purposes.

TRANSLATED_TEXTS = {
    # Spanish translations (es)
    "es_greeting": "[mock-es] Hola, mundo!", # Correct
    "es_question": "[mock-es] Cómo estás today?", # Intentional error: "today?" not translated
    "es_statement_long": "[mock-es] El rápido zorro marrón salta sobre el perro perezoso. Esta frase contiene todas las letras del alfabeto.", # Correct
    "es_technical_term": "[mock-es] El sistema requiere un cortafuegos robusto.", # Correct
    "es_idiom": "[mock-es] Está lloviendo perros y gatos.", # Literal translation, idiomatically incorrect

    # French translations (fr)
    "fr_greeting": "[mock-fr] Bonjour, monde!", # Correct
    "fr_question": "[mock-fr] Comment ça va aujourd'hui?", # Correct
    "fr_statement_long": "[mock-fr] Le renard brun rapide saute par-dessus le chien paresseux. Cette phrase contient toutes les lettres de l'alphabet.", # Correct
    "fr_technical_term": "[mock-fr] Le système exige un pare-feu robuste.", # Correct, "exige" is a bit strong but plausible
    "fr_idiom": "[mock-fr] Il pleut des chats et des chiens." # Literal translation, idiomatically incorrect
}

# Examples of how these might be structured if generated by a script:
# "original_key": {
# "target_language_1": "translation_1",
# "target_language_2": "translation_2",
# }
# For instance:
# "en_greeting": {
# "es": "[mock-es] Hola, mundo!",
# "fr": "[mock-fr] Bonjour, monde!"
# }
# However, for simplicity in this example, we are using a flat structure
# with language prefixes in the keys.
